services:
  ejabberd:
    image: ejabberd/ecs:latest
    container_name: xmpp-broker
    ports:
      - "5222:5222"   # XMPP client
      - "5280:5280"   # Admin UI
    environment:
      - EJABBERD_ADMIN_PASSWORD=admin_pwd
      # ejabberd’s default vhost is 'localhost'

  app:
    build: .
    container_name: retail-app
    depends_on:
      - ejabberd
    ports:
      - "5000:5000"  # Flask dashboard
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    network_mode: "service:ejabberd"